### PR TITLE
fix: Force re-config exporter when upgrade

### PR DESCRIPTION
**Pull request by jneo8**

### CODE REVIEW

**Review by chanchiwai-ray — APPROVED** [review]
Approve because this PR is against a dev branch, and that we may want to reinstall the exporter due to charm upgrade (e.g. the charm pull a new version of [exporter](https://github.com/canonical/prometheus-hardware-exporter)) in the next release

**Review by Pjack — CHANGES_REQUESTED** [review]
It's reasonable to me to re-install exporter after upgrade charm.
I want to confirm some behavior

1. Will we restart the exporter service? I cannot find related trigger point
Ray/Ashley also suggested that we can always start the exporter after the installation to reduce the complexity.

2. Will the relation been refresh?  so alert rule will be updated.

3. Attach-resource will trigger the same procedure with upgrade charm. Will it be a problem?

**Comment by chanchiwai-ray** [comment]
> It's reasonable to me to re-install exporter after upgrade charm. I want to confirm some behavior
> 
>     1. Will we restart the exporter service? I cannot find related trigger point
>        Ray/Ashley also suggested that we can always start the exporter after the installation to reduce the complexity.
> 
>     2. Will the relation been refresh?  so alert rule will be updated.
> 
>     3. Attach-resource will trigger the same procedure with upgrade charm. Will it be a problem?

I only know (2): no it will not. This is related to another issue #127

**Comment by jneo8** [comment]
> It's reasonable to me to re-install exporter after upgrade charm. I want to confirm some behavior
> 
> 1. Will we restart the exporter service? I cannot find related trigger point
>    Ray/Ashley also suggested that we can always start the exporter after the installation to reduce the complexity.

No, we don't restart exporter. Let me update it.

> 2. Will the relation been refresh?  so alert rule will be updated.

No, it's another bug mention by Ray in previous comment.

> 3. Attach-resource will trigger the same procedure with upgrade charm. Will it be a problem?

No, just take more time to render config and restart exporter.

**Review by Pjack — APPROVED** [review]

**Pull request merged**
