### PR TITLE
Add noble support

### PR DESCRIPTION
**Pull request by samuelallan72**
Note: we cannot add functional tests for noble, because this is a subordinate charm and we don't have any other principle charms that support noble yet.

I did add functional tests for focal; they were missing from CI.

### CODE REVIEW

**Comment by samuelallan72** [comment]
I think this is failing because the workflow is using charmcraft 3, and charmcraft 3 maybe only supports noble using the new syntax?  I've opened https://github.com/canonical/solutions-engineering-automation/pull/79 to update this repo with our latest check template which pins charmcraft to v2.

**Review by Pjack — APPROVED** [review]

**Review by aieri — APPROVED** [review]

**Comment by samuelallan72** [comment]
Hmm actually there must be something wrong with the check.yaml workflow, because it's not running... I wish github gave an error rather than silently ignored broken workflow files :confused:

**Comment by samuelallan72** [comment]
Reverted the changes to check.yaml.

**Comment by samuelallan72** [comment]
Hmm maybe the promtool tests workflow is overriding check.yaml?  I checked the PR where I introduced that, and the check.yaml workflow wasn't running there either: https://github.com/canonical/hardware-observer-operator/pull/310 :/  We really need to add the list of workflows required to the protection rules.

**Comment by samuelallan72** [comment]
They're all running in https://github.com/canonical/hardware-observer-operator/pull/311 , so maybe we can merge that first. :)

**Review by jneo8 — APPROVED** [review]

**Review by chanchiwai-ray — APPROVED** [review]

**Pull request merged**
