### PR TITLE
Add redfish alert rules

### PR DESCRIPTION
**Pull request by dashmage**
Also add unit tests for alert rules.

### CODE REVIEW

**Comment by dashmage** [comment]
The diff for `src/prometheus_alert_rules/redfish.yaml` contains more changes due to formatting done to the previously existing rules

**Review by sudeephb — APPROVED** [review]
LGTM

**Review by Pjack — COMMENTED** [review]
I have a question. These alert rule looks very common. 
If there are 2 identical server in the cluster, will the same alert rule been added into alert manager twice?  And then we receive 2 notifications but there is only 1 server unhealthly.

**Comment by dashmage** [comment]
> If there are 2 identical server in the cluster, will the same alert rule been added into alert manager twice? And then we receive 2 notifications but there is only 1 server unhealthly.

Along with each of the alert rules we are also putting the instance (in the summary) and the LABEL (in the description). This will allow us to identify which server instance is the error coming from and also from the LABEL we can see which is the processor id, model, chassis id etc.

Hope that answers your question.

**Comment by Pjack** [comment]
> > If there are 2 identical server in the cluster, will the same alert rule been added into alert manager twice? And then we receive 2 notifications but there is only 1 server unhealthly.
> 
> Along with each of the alert rules we are also putting the instance (in the summary) and the LABEL (in the description). This will allow us to identify which server instance is the error coming from and also from the LABEL we can see which is the processor id, model, chassis id etc.
> 
> Hope that answers your question.

The code looks good to me. We can merge it.
But as we discussed offline, let's confirm the behavior for multiple identical server after we get the patch in grafana-agent. The expected behavior is:

* 1 alert rule when there are two identical servers, 
* it will be triggered whenever any one of the server failed
* it will be triggered twice notification when there are two servers failed.

**Review by Pjack — APPROVED** [review]

**Pull request merged**
